name: Build & Test FeedTrac

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
        
    - name: Restore Server
      working-directory: FeedTrac.Server
      run: dotnet restore

    - name: Build Server
      working-directory: FeedTrac.Server
      run: dotnet build --no-restore --configuration Release

    - name: Restore Tests
      if: exists('FeedTrac.Tests')
      working-directory: FeedTrac.Tests
      run: dotnet restore

    - name: Build Tests
      if: exists('FeedTrac.Tests')
      working-directory: FeedTrac.Tests
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      if: exists('FeedTrac.Tests')
      working-directory: FeedTrac.Tests
      run: dotnet test --no-build --configuration Release
